POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id":"ddd REST",
    "price": 850.9,
    "tax": 1.3
}

###

GET http://localhost:8000/order/list HTTP/1.1
Host: localhost:8000
Content-Type: application/json
